Traceback (most recent call last):
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\asyncio\base_events.py", line 647, in run_until_complete
    return future.result()
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\Jim\anaconda3\envs\jupyter-book-3-9\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
from jupyterquiz import display_quiz

path = "./example_questions.json"

display_quiz(path)

git_path="https://raw.githubusercontent.com/jmshea/jupyterquiz/main/examples/"
display_quiz(git_path+"questions.json")
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Cell [1;32mIn [1], line 1[0m
[1;32m----> 1[0m [38;5;28;01mfrom[39;00m [38;5;21;01mjupyterquiz[39;00m [38;5;28;01mimport[39;00m display_quiz
[0;32m      3[0m path [38;5;241m=[39m [38;5;124m"[39m[38;5;124m./example_questions.json[39m[38;5;124m"[39m
[0;32m      5[0m display_quiz(path)

[1;31mModuleNotFoundError[0m: No module named 'jupyterquiz'
ModuleNotFoundError: No module named 'jupyterquiz'

